name: NodeJS CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # See https://nodejs.org/en/about/releases/
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use NodeJS ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install, lint and test
              run: |
                  npm install
                  npm link
                  npm run lint
                  npm test
